<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Diet Report - {{ $user->name }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #1a202c; margin: 0; padding: 20px; }
        .header { background: linear-gradient(135deg, #2d6a4f, #40916c); color: white; padding: 24px; border-radius: 8px; margin-bottom: 24px; }
        .header h1 { margin: 0; font-size: 22px; }
        .header p { margin: 4px 0 0; opacity: 0.85; font-size: 13px; }
        .section { margin-bottom: 20px; }
        .section h2 { font-size: 14px; color: #2d6a4f; border-bottom: 2px solid #95d5b2; padding-bottom: 4px; margin-bottom: 12px; }
        .grid { display: table; width: 100%; }
        .col { display: table-cell; width: 33%; padding: 4px 8px 4px 0; vertical-align: top; }
        .metric-box { background: #f0fdf4; border: 1px solid #95d5b2; border-radius: 6px; padding: 10px; text-align: center; margin: 4px; }
        .metric-box .val { font-size: 20px; font-weight: bold; color: #2d6a4f; }
        .metric-box .lbl { font-size: 10px; color: #666; margin-top: 2px; }
        table.meal { width: 100%; border-collapse: collapse; font-size: 11px; margin-top: 8px; }
        table.meal th { background: #2d6a4f; color: white; padding: 6px 8px; text-align: left; }
        table.meal td { padding: 5px 8px; border-bottom: 1px solid #e2e8f0; }
        table.meal tr:nth-child(even) td { background: #f7fffe; }
        .meal-header { background: #d8f3dc; color: #1b4332; font-weight: bold; padding: 6px 8px; border-radius: 4px; margin-top: 10px; font-size: 12px; }
        .footer { text-align: center; font-size: 10px; color: #999; margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 12px; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 10px; font-weight: bold; }
        .badge-green { background: #d1fae5; color: #065f46; }
        .badge-yellow { background: #fef9c3; color: #713f12; }
        .badge-red { background: #fee2e2; color: #991b1b; }
    </style>
</head>
<body>

<div class="header">
    <h1>🥗 Personalized Diet Report</h1>
    <p>{{ $user->name }} &nbsp;|&nbsp; {{ $date }} &nbsp;|&nbsp; Generated by Diet & Nutrition Planner</p>
</div>

<!-- Health Metrics -->
@if($user->profile)
<div class="section">
    <h2>📊 Health Metrics</h2>
    <div class="grid">
        <div class="col">
            <div class="metric-box">
                <div class="val">{{ $user->profile->bmi ?? '—' }}</div>
                <div class="lbl">BMI</div>
            </div>
        </div>
        <div class="col">
            <div class="metric-box">
                <div class="val">{{ $user->profile->bmr ?? '—' }}</div>
                <div class="lbl">BMR (kcal/day)</div>
            </div>
        </div>
        <div class="col">
            <div class="metric-box">
                <div class="val">{{ $user->profile->tdee ?? '—' }}</div>
                <div class="lbl">TDEE (kcal/day)</div>
            </div>
        </div>
        <div class="col">
            <div class="metric-box">
                <div class="val">{{ $user->profile->calories_target ?? '—' }}</div>
                <div class="lbl">Calorie Target</div>
            </div>
        </div>
        <div class="col">
            <div class="metric-box">
                <div class="val">{{ $user->profile->weight_kg ?? '—' }} kg</div>
                <div class="lbl">Weight</div>
            </div>
        </div>
        <div class="col">
            <div class="metric-box">
                <div class="val">{{ ucfirst($user->profile->goal ?? '—') }}</div>
                <div class="lbl">Goal</div>
            </div>
        </div>
    </div>
</div>
@endif

<!-- Meal Plan -->
@if($plan)
<div class="section">
    <h2>🍽️ Meal Plan for {{ $date }}</h2>

    @php
        $mealIcons = ['breakfast' => '🌅', 'lunch' => '☀️', 'snack' => '🫐', 'dinner' => '🌙'];
        $grouped = $plan->mealItems->groupBy('meal_type');
    @endphp

    @foreach(['breakfast', 'lunch', 'snack', 'dinner'] as $mealType)
        @if(isset($grouped[$mealType]))
        <div class="meal-header">{{ $mealIcons[$mealType] }} {{ ucfirst($mealType) }}</div>
        <table class="meal">
            <tr>
                <th>Food Item</th>
                <th>Qty</th>
                <th>Calories</th>
                <th>Protein</th>
                <th>Carbs</th>
                <th>Fat</th>
            </tr>
            @foreach($grouped[$mealType] as $item)
            <tr>
                <td>{{ $item->food->name ?? 'N/A' }}</td>
                <td>{{ $item->quantity }}{{ $item->unit }}</td>
                <td>{{ $item->calories }} kcal</td>
                <td>{{ $item->protein }}g</td>
                <td>{{ $item->carbs }}g</td>
                <td>{{ $item->fat }}g</td>
            </tr>
            @endforeach
        </table>
        @endif
    @endforeach

    <div class="grid" style="margin-top: 12px;">
        <div class="col"><div class="metric-box"><div class="val">{{ $plan->total_calories }}</div><div class="lbl">Total Calories</div></div></div>
        <div class="col"><div class="metric-box"><div class="val">{{ $plan->protein_target }}g</div><div class="lbl">Protein</div></div></div>
        <div class="col"><div class="metric-box"><div class="val">{{ $plan->water_intake_liters }}L</div><div class="lbl">Water Intake</div></div></div>
    </div>
</div>
@else
<p style="color:#999;">No meal plan found for {{ $date }}.</p>
@endif

<!-- Recent Progress -->
@if($recentLogs->count())
<div class="section">
    <h2>📈 Recent 7-Day Progress</h2>
    <table class="meal">
        <tr>
            <th>Date</th><th>Weight (kg)</th><th>Calories Eaten</th><th>Water (L)</th><th>Steps</th><th>Workout</th>
        </tr>
        @foreach($recentLogs as $log)
        <tr>
            <td>{{ $log->date }}</td>
            <td>{{ $log->weight ?? '—' }}</td>
            <td>{{ $log->calories_consumed ?? '—' }}</td>
            <td>{{ $log->water_intake_liters ?? '—' }}</td>
            <td>{{ $log->steps ?? '—' }}</td>
            <td>{{ $log->workout_done ? '✅' : '❌' }}</td>
        </tr>
        @endforeach
    </table>
</div>
@endif

<div class="footer">
    This report is generated by Diet & Nutrition Planner &bull; Based on WHO/NIH/CDC guidelines &bull; {{ now()->format('d M Y, h:i A') }}
</div>

</body>
</html>
